pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: StorageVariables

steps:

  # Set up Python environment
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Install necessary Python dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Generate SBOM using CycloneDX based on requirements.txt
  - script: |
      pip install cyclonedx-bom
      cyclonedx-py requirements -o reports/sbom.json
    displayName: 'Generate SBOM using CycloneDX'

  # Download NVD Data using API Key
  - script: |
      curl -H "apiKey: ${NVD_API_KEY}" "https://services.nvd.nist.gov/rest/json/cves/1.0?startIndex=0&resultsPerPage=10" > nvd-cve-data.json
    displayName: 'Download NVD Data'

  # Set up Dependency-Check
  - script: |
      wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
      unzip dependency-check-10.0.4-release.zip -d dependency-check
      chmod +x dependency-check/bin/dependency-check.sh
      echo "Directory contents after extraction:"
      ls -R
      export PATH=$(pwd)/dependency-check/bin:$PATH
      echo "nvd.api.key=${NVD_API_KEY}" > dependency-check.properties
    displayName: 'Download and Set Up OWASP Dependency-Check'

  # Run OWASP Dependency-Check
  - script: |
      dependency-check/bin/dependency-check.sh \
      --project "pygoat-python" \
      --out "$(Build.SourcesDirectory)/dependency-check-report" \
      --scan "$(Build.SourcesDirectory)" \
      --data "$(Build.SourcesDirectory)/nvd-data" \
      --format ALL --failOnCVSS 7
    displayName: 'Run OWASP Dependency-Check using Pre-Downloaded NVD Data'

  - script: |
      if [ ! -d "$(Build.SourcesDirectory)/dependency-check-report" ]; then
        echo "Directory $(Build.SourcesDirectory)/dependency-check-report does not exist."
        exit 1
      fi
      echo "Directory exists."
    displayName: 'Check if Dependency-Check Report Directory Exists'

  # Upload Dependency-Check Report to Azure Blob Storage
  - script: |
      tar -czvf $(Build.SourcesDirectory)/dependency-check-report.tar.gz -C $(Build.SourcesDirectory) dependency-check-report
      echo "Tarball created:"
      ls -l $(Build.SourcesDirectory)/dependency-check-report.tar.gz

      az storage blob upload \
        --container-name test \
        --name dependency-check-report.tar.gz \
        --file $(Build.SourcesDirectory)/dependency-check-report.tar.gz \
        --connection-string "$(AZURE_STORAGE_CONNECTION_STRING)" \
        --overwrite
    displayName: 'Upload Dependency-Check Report to Azure Storage'
