pool:
  vmImage: 'ubuntu-latest'
variables:
  NVD_API_KEY: '854a248e-c7f6-4107-aac2-207fb9cab9c5'


steps:


  # Set up Python environment
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Install necessary Python dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Generate SBOM using CycloneDX based on requirements.txt
  - script: |
      pip install cyclonedx-bom
      cyclonedx-py requirements -o reports/sbom.json
    displayName: 'Generate SBOM using CycloneDX'

  # Run OWASP Dependency-Check
  - task: dependency-check-build-task@6
    inputs:
      projectName: 'pygoat-python'  # Specify your project name here
      scanPath: '$(Build.SourcesDirectory)/src'
      outputFormat: 'ALL'
      failOnCVSS: '7'
    env:
      NVD_API_KEY: $(NVD_API_KEY)  # Pass the NVD API key from the pipeline environment variables


    displayName: 'Run OWASP Dependency-Check'

  # Publish the Dependency-Check report to Azure Storage Account


