pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: StorageVariables

stages:
  - stage: AnalysisAndScanning
    displayName: 'Security Scanning'
    jobs:
      - job: SecurityScanning
        displayName: 'Trivy'
        steps:
          - script: |
              sudo apt-get install -y wget
              wget -q https://github.com/aquasecurity/trivy/releases/download/v0.33.0/trivy_0.33.0_Linux-64bit.deb
              sudo dpkg -i trivy_0.33.0_Linux-64bit.deb
          - script: |
              trivy fs --exit-code 0 --severity CRITICAL,HIGH,MEDIUM,LOW --format cyclonedx --output $(Build.ArtifactStagingDirectory)/trivy-repo-sbom.json .
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'az-storageaccount-access-test'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage blob upload \
                  --account-name viswajithcloudshellsa \
                  --container-name test \
                  --file $(Build.ArtifactStagingDirectory)/trivy-repo-sbom.json \
                  --name trivy-repo-sbom.json \
                  --overwrite
                  --connection-string $(AZURE_STORAGE_CONNECTION_STRING)
  - stage: BuildAndScanImage
    displayName: 'Build and Image Scan'
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'sumedhdocker'
              repository: 'sumedh03/test'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'

      - job: ImageScan
        displayName: 'Trivy Image Scan'
        dependsOn: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'sumedhdocker'
              command: 'login'
          - script: |
              sudo apt-get update
              sudo apt-get install -y wget
              wget -q https://github.com/aquasecurity/trivy/releases/download/v0.33.0/trivy_0.33.0_Linux-64bit.deb
              sudo dpkg -i trivy_0.33.0_Linux-64bit.deb
          - script: |
              trivy image --exit-code 0 --severity CRITICAL,HIGH,MEDIUM,LOW --format cyclonedx --output $(Build.ArtifactStagingDirectory)/image-sbom.json $(sumedhdocker)/sumedh03/test:$(Build.BuildId)
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'az-storageaccount-access-test'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage blob upload \
                  --account-name viswajithcloudshellsa \
                  --container-name test \
                  --file $(Build.ArtifactStagingDirectory)/image-sbom.json \
                  --name image-sbom.json \
                  --overwrite
                  --connection-string $(AZURE_STORAGE_CONNECTION_STRING)