pool:
  vmImage: 'ubuntu-latest'

variables:
  NVD_API_KEY: 'a254d0f1-951c-47d2-baac-f88712b7b7a3'

steps:

  # Set up Python environment
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Install necessary Python dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Generate SBOM using CycloneDX based on requirements.txt
  - script: |
      pip install cyclonedx-bom
      cyclonedx-py requirements -o reports/sbom.json
    displayName: 'Generate SBOM using CycloneDX'
  - script: |
      wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
      unzip dependency-check-10.0.4-release.zip -d dependency-check
      export PATH=$(pwd)/dependency-check/bin:$PATH
      dependency-check/bin/dependency-check.sh --updateonly --cveValidForHours 168 --data nvd-data
      git add nvd-data
      git commit -m "Add NVD data to repository"
      git push origin master

    displayName: 'Download and Set Up OWASP Dependency-Check'
  # Print environment variables for debugging
  - script: |
      echo "NVD_API_KEY=${NVD_API_KEY}"
    displayName: 'Print Environment Variables'
  - script: |
      echo "nvd.api.key=${NVD_API_KEY}" > dependency-check.properties
    displayName: 'Create Dependency-Check Properties File'
  # Run OWASP Dependency-Check
  - script: |
      dependency-check/bin/dependency-check.sh \
      --project "pygoat-python" \
      --out "$(Build.SourcesDirectory)/dependency-check-report" \
      --scan "$(Build.SourcesDirectory)" \
      --data "$(Build.SourcesDirectory)/nvd-data" \
      --format ALL --failOnCVSS 7
    displayName: 'Run OWASP Dependency-Check using Pre-Downloaded NVD Data'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/dependency-check-report'
      ArtifactName: 'DependencyCheckReport'
    displayName: 'Publish Dependency-Check Report'

  # Publish the Dependency-Check report to Azure Storage Account
